version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: data-plumber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  mongodb:
    image: mongo:6 
    ports:
      - "27027:27017"
    volumes: 
      - mongodb_data:/data/mongodb 
    command: ["mongod", "--profile", "2"]  
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword

  redis:
    image: redis:latest 
    ports:
      - "6379:6379" 
    volumes: 
      - redis_data:/data

volumes:
  mongodb_data: 
  redis_data: